# Generated by Django 4.1.7 on 2023-04-04 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "hackathon_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("file", "file"), ("image", "image"), ("url", "url")],
                        max_length=15,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("reward_prize", models.PositiveBigIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HackathonSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("description", models.TextField()),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hackathon"
                    ),
                ),
                (
                    "starred_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favourite_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hackathon_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="hackathon",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gte", models.F("start_time"))),
                name="correct end time",
                violation_error_message="End time should be greater than starting time",
            ),
        ),
    ]
